In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
#타이타닉 호 승객 생존 예측 프로젝트
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

df = pd.read_csv("titanic_processedData.csv")

In [3]:
#데이터 X와 정답 y
#X [선실등급, 성별, 나이, 부부형제 수, 부모자식 수, 운임]
x_cols = ['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare']
X = df[x_cols].values
X

array([[  1.    ,   1.    ,  29.    ,   0.    ,   0.    , 211.3375],
       [  1.    ,   0.    ,   0.9167,   1.    ,   2.    , 151.55  ],
       [  1.    ,   1.    ,   2.    ,   1.    ,   2.    , 151.55  ],
       ...,
       [  3.    ,   0.    ,  26.5   ,   0.    ,   0.    ,   7.225 ],
       [  3.    ,   0.    ,  27.    ,   0.    ,   0.    ,   7.225 ],
       [  3.    ,   0.    ,  29.    ,   0.    ,   0.    ,   7.875 ]])

In [4]:
# y
y = df['survived'].values
y

#데이터 전처리 완료

array([1, 1, 0, ..., 0, 0, 0])

### ML 코딩 5단계
#### 1. 훈련 데이터와 테스트 데이터 준비
#### 2. ML 알고리즘 선택
#### 3. 훈련 (under fitting, over fitting 조심)
#### 4. 평가
#### 5. 새 데이터로 예측

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=13)
X_train

array([[ 2.    ,  0.    , 27.    ,  0.    ,  0.    , 13.    ],
       [ 1.    ,  0.    , 36.    ,  0.    ,  0.    , 26.3875],
       [ 3.    ,  1.    , 22.    ,  3.    ,  1.    , 25.4667],
       ...,
       [ 1.    ,  0.    , 33.    ,  0.    ,  0.    , 52.    ],
       [ 1.    ,  1.    , 37.    ,  1.    ,  0.    , 51.8625],
       [ 2.    ,  0.    , 28.    ,  0.    ,  0.    , 26.    ]])